### ISSUE TITLE
FAILS TO LOAD FRAME  (video loads on server for 2sec maxium then stays static)

### ISSUE THREAD

**Issue by 9ninth** [bitsanndbytes/Webrtc-python#1]
![Screenshot (7)](https://github.com/bitsanndbytes/Webrtc-python/assets/158848182/e668e0df-df2d-43fd-b3fc-8ffad2325f66)
   [flv @ 000001d58272e340] unsupported amf type 17
[rtmp @ 000001d58272ee00] Server error: Insufficient bandwidth to play 
[ WARN:0@8.858] global cap_ffmpeg_impl.hpp:1541 grabFrame packet read max attempts exceeded, if your video have multiple streams (video, audio) try to increase attempt limit by setting environment variable OPENCV_FFMPEG_READ_ATTEMPTS (current value is 4096)
WARNING:aiortc.rtcrtpsender:RTCRtpsender(video) Traceback (most recent call last):
  File "C:\Users\juani\PycharmProjects\pythonProject1\.venv\lib\site-packages\aiortc\rtcrtpsender.py", line 328, in _run_rtp
    enc_frame = await self._next_encoded_frame(codec)
  File "C:\Users\juani\PycharmProjects\pythonProject1\.venv\lib\site-packages\aiortc\rtcrtpsender.py", line 270, in _next_encoded_frame
    data = await self.__track.recv()
  File "C:\Users\juani\PycharmProjects\pythonProject1\webcam.py", line 84, in recv
    raise RuntimeError("Failed to read frame from the camera.")
RuntimeError: Failed to read frame from the camera.

INFO:aioice.ice:Connection(0) Check CandidatePair(('2607:fb91:160b:d8e3:48f0:9d2f:8d4e:91f9', 49647) -> ('2607:fb91:160b:d8e3:48f0:9d2f:8d4e:91f9', 51849)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2607:fb91:160b:d8e3:7a69:ce69:a2d9:9562', 49648) -> ('2607:fb91:160b:d8e3:7a69:ce69:a2d9:9562', 51849)) State.IN_PROGRESS -> State.FAILED
INFO:aioice.ice:Connection(0) Check CandidatePair(('2607:fb91:160b:d8e3:940d:94d8:76c2:c7eb', 49649) -> ('2607:fb91:160b:d8e3:940d:94d8:76c2:c7eb', 51849)) State.IN_PROGRESS -> State.FAILED

**Comment by bitsanndbytes** [comment]
Issues was with ip cameras not fully stated, closing this issue
